# Generated by Django 5.1.4 on 2024-12-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no',
            field=models.IntegerField(unique=True),
        ),
    ]
