# Generated by Django 5.1.4 on 2024-12-11 16:13

import billing.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performa_name', models.FileField(upload_to=billing.models.performa_path)),
                ('performa_created_at', models.DateTimeField(auto_now_add=True)),
                ('performa_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customermodel')),
            ],
        ),
    ]
