# Generated by Django 5.1.4 on 2024-12-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customermodel_performamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksmodel',
            old_name='product_quantity',
            new_name='product_stock',
        ),
    ]
