# Generated by Django 5.1.4 on 2024-12-29 17:29

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_customermodel_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
