# Generated by Django 5.1.4 on 2024-12-29 18:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_customermodel_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
