# Generated by Django 5.1.4 on 2024-12-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_companydetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsmodel',
            name='data_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
