# Generated by Django 5.1.4 on 2024-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_companydetailsmodel_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsmodel',
            name='bill_type',
            field=models.CharField(blank=True, default='Invoice', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='invoice_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
