# Generated by Django 5.1.4 on 2024-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_companydetailsmodel_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='data_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
